USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS WH_YELP_XS
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS YELP_WEATHER;
USE DATABASE YELP_WEATHER;

CREATE SCHEMA IF NOT EXISTS STG;
CREATE SCHEMA IF NOT EXISTS ODS;
CREATE SCHEMA IF NOT EXISTS DWH;
CREATE SCHEMA IF NOT EXISTS UTIL;

CREATE OR REPLACE FILE FORMAT UTIL.JSON_NDJSON_FF
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE;

CREATE OR REPLACE FILE FORMAT UTIL.CSV_FF
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '\"'
  SKIP_HEADER = 1
  NULL_IF = ('','NULL')
  EMPTY_FIELD_AS_NULL = TRUE
  TRIM_SPACE = TRUE;

CREATE OR REPLACE STAGE STG.YELP_STAGE    FILE_FORMAT = UTIL.JSON_NDJSON_FF;
CREATE OR REPLACE STAGE STG.CLIMATE_STAGE FILE_FORMAT = UTIL.CSV_FF;
