USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_YELP_XS;
USE DATABASE YELP_WEATHER;
USE SCHEMA STG;

-- Raw Yelp JSON staged as VARIANT
CREATE OR REPLACE TABLE BUSINESS_RAW  (V VARIANT);
CREATE OR REPLACE TABLE REVIEW_RAW    (V VARIANT);
CREATE OR REPLACE TABLE TIP_RAW       (V VARIANT);
CREATE OR REPLACE TABLE CHECKIN_RAW   (V VARIANT);
CREATE OR REPLACE TABLE COVID_RAW     (V VARIANT);
CREATE OR REPLACE TABLE CUSTOMER_RAW  (V VARIANT);

-- Raw climate CSVs (columns match the source files)
CREATE OR REPLACE TABLE TEMPERATURE_RAW (
  DATE_RAW STRING,
  TMIN_F FLOAT,
  TMAX_F FLOAT,
  NORMAL_TMIN_F FLOAT,
  NORMAL_TMAX_F FLOAT
);

CREATE OR REPLACE TABLE PRECIPITATION_RAW (
  DATE_RAW STRING,
  PRECIP_IN FLOAT,
  PRECIP_NORMAL_IN FLOAT
);
