USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_YELP_XS;
USE DATABASE YELP_WEATHER;
USE SCHEMA STG;

-- Yelp NDJSON batches into VARIANT staging tables
COPY INTO STG.BUSINESS_RAW
  FROM @STG.YELP_STAGE
  PATTERN = '.*business_part_.*\\.gz'
  FILE_FORMAT = (FORMAT_NAME = 'UTIL.JSON_NDJSON_FF')
  ON_ERROR = 'CONTINUE';

COPY INTO STG.REVIEW_RAW
  FROM @STG.YELP_STAGE
  PATTERN = '.*review_part_.*\\.gz'
  FILE_FORMAT = (FORMAT_NAME = 'UTIL.JSON_NDJSON_FF')
  ON_ERROR = 'CONTINUE';

COPY INTO STG.CUSTOMER_RAW
  FROM @STG.YELP_STAGE
  PATTERN = '.*user_part_.*\\.gz'
  FILE_FORMAT = (FORMAT_NAME = 'UTIL.JSON_NDJSON_FF')
  ON_ERROR = 'CONTINUE';

COPY INTO STG.CHECKIN_RAW
  FROM @STG.YELP_STAGE
  PATTERN = '.*checkin_part_.*\\.gz'
  FILE_FORMAT = (FORMAT_NAME = 'UTIL.JSON_NDJSON_FF')
  ON_ERROR = 'CONTINUE';

COPY INTO STG.TIP_RAW
  FROM @STG.YELP_STAGE
  PATTERN = '.*tip_part_.*\\.gz'
  FILE_FORMAT = (FORMAT_NAME = 'UTIL.JSON_NDJSON_FF')
  ON_ERROR = 'CONTINUE';

COPY INTO STG.COVID_RAW
  FROM @STG.YELP_STAGE
  PATTERN = '.*covid_part_.*\\.gz'
  FILE_FORMAT = (FORMAT_NAME = 'UTIL.JSON_NDJSON_FF')
  ON_ERROR = 'CONTINUE';

-- Climate CSVs (explicit filenames to pick up AUTO_COMPRESS=TRUE uploads)
COPY INTO STG.TEMPERATURE_RAW
  FROM @STG.CLIMATE_STAGE
  FILES = ('temperature.csv.gz')
  FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FF')
  ON_ERROR = 'CONTINUE';

COPY INTO STG.PRECIPITATION_RAW
  FROM @STG.CLIMATE_STAGE
  FILES = ('precipitation.csv.gz')
  FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FF')
  ON_ERROR = 'CONTINUE';

-- Evidence for staging load
SELECT table_name, row_count
FROM INFORMATION_SCHEMA.TABLES
WHERE table_schema = 'STG'
  AND table_name IN (
    'BUSINESS_RAW','REVIEW_RAW','CUSTOMER_RAW','CHECKIN_RAW','TIP_RAW','COVID_RAW',
    'TEMPERATURE_RAW','PRECIPITATION_RAW')
ORDER BY table_name;
