USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_YELP_XS;
USE DATABASE YELP_WEATHER;

-- ODS typed tables
CREATE OR REPLACE TABLE ODS.BUSINESS (
  BUSINESS_ID STRING PRIMARY KEY,
  NAME STRING, ADDRESS STRING, CITY STRING, STATE STRING, POSTAL_CODE STRING,
  LATITUDE NUMBER(9,6), LONGITUDE NUMBER(9,6),
  STARS NUMBER(3,2), REVIEW_COUNT NUMBER, IS_OPEN NUMBER,
  CATEGORIES STRING,
  HOURS_MON STRING, HOURS_TUE STRING, HOURS_WED STRING, HOURS_THU STRING, HOURS_FRI STRING, HOURS_SAT STRING, HOURS_SUN STRING,
  RAW VARIANT
);

CREATE OR REPLACE TABLE ODS.CUSTOMER (
  CUSTOMER_ID STRING PRIMARY KEY,
  YELPING_SINCE DATE, REVIEW_COUNT NUMBER,
  FRIENDS_COUNT NUMBER, USEFUL_VOTES NUMBER, FUNNY_VOTES NUMBER, COOL_VOTES NUMBER,
  ELITE_RAW STRING,
  RAW VARIANT
);

CREATE OR REPLACE TABLE ODS.REVIEW (
  REVIEW_ID STRING PRIMARY KEY,
  BUSINESS_ID STRING, CUSTOMER_ID STRING,
  STARS NUMBER(2,1),
  USEFUL NUMBER, FUNNY NUMBER, COOL NUMBER,
  REVIEW_DATE DATE,
  RAW VARIANT
);

CREATE OR REPLACE TABLE ODS.TIP (
  BUSINESS_ID STRING, CUSTOMER_ID STRING,
  TIP_DATE DATE, COMPLIMENT_COUNT NUMBER, TEXT STRING,
  RAW VARIANT
);

CREATE OR REPLACE TABLE ODS.CHECKIN (
  BUSINESS_ID STRING,
  CHECKINS_COUNT NUMBER,
  RAW VARIANT
);

CREATE OR REPLACE TABLE ODS.COVID (
  BUSINESS_ID STRING,
  DELIVERY_OR_TAKEOUT BOOLEAN,
  GRUBHUB BOOLEAN, DOORDASH BOOLEAN, UBEREATS BOOLEAN,
  RAW VARIANT
);

CREATE OR REPLACE TABLE ODS.TEMPERATURE (
  WX_DATE DATE PRIMARY KEY,
  TMIN_F FLOAT, TMAX_F FLOAT, NORMAL_MIN_F FLOAT, NORMAL_MAX_F FLOAT
);

CREATE OR REPLACE TABLE ODS.PRECIPITATION (
  WX_DATE DATE PRIMARY KEY,
  PRECIP_IN FLOAT, PRECIP_NORMAL_IN FLOAT
);
