USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_YELP_XS;
USE DATABASE YELP_WEATHER;
USE SCHEMA ODS;

CREATE OR REPLACE VIEW ODS.REVIEW_WITH_WEATHER AS
SELECT
  r.REVIEW_ID,
  r.CUSTOMER_ID,
  r.BUSINESS_ID,
  b.NAME  AS BUSINESS_NAME,
  b.CITY,
  b.STATE,
  r.REVIEW_DATE,
  r.STARS,
  t.TMIN_F,
  t.TMAX_F,
  t.NORMAL_MIN_F,
  t.NORMAL_MAX_F,
  p.PRECIP_IN,
  p.PRECIP_NORMAL_IN
FROM ODS.REVIEW r
JOIN ODS.BUSINESS b USING (BUSINESS_ID)
LEFT JOIN ODS.TEMPERATURE   t ON t.WX_DATE = r.REVIEW_DATE
LEFT JOIN ODS.PRECIPITATION p ON p.WX_DATE = r.REVIEW_DATE
WHERE b.STATE IS NOT NULL;

-- Evidence for integration
SELECT COUNT(*) AS REVIEW_WITH_WEATHER_ROWS FROM ODS.REVIEW_WITH_WEATHER;
SELECT STATE, COUNT(*) AS REVIEW_ROWS
FROM ODS.REVIEW_WITH_WEATHER
GROUP BY STATE
ORDER BY REVIEW_ROWS DESC
LIMIT 10;
