USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_YELP_XS;
USE DATABASE YELP_WEATHER;
USE SCHEMA DWH;

-- Date dimension from distinct review dates
CREATE OR REPLACE TABLE DIM_DATE (
  DATE_KEY INT PRIMARY KEY,
  FULL_DATE DATE,
  YEAR INT,
  MONTH INT,
  DAY INT,
  DAY_NAME STRING,
  WEEK INT
);

INSERT OVERWRITE INTO DIM_DATE
SELECT
  TO_NUMBER(TO_CHAR(REVIEW_DATE, 'YYYYMMDD')) AS DATE_KEY,
  REVIEW_DATE,
  YEAR(REVIEW_DATE),
  MONTH(REVIEW_DATE),
  DAY(REVIEW_DATE),
  DAYNAME(REVIEW_DATE),
  WEEK(REVIEW_DATE)
FROM (SELECT DISTINCT REVIEW_DATE FROM ODS.REVIEW_WITH_WEATHER)
WHERE REVIEW_DATE IS NOT NULL
ORDER BY DATE_KEY;

-- Business dimension
CREATE OR REPLACE TABLE DIM_BUSINESS (
  BUSINESS_KEY INT AUTOINCREMENT PRIMARY KEY,
  BUSINESS_ID STRING UNIQUE,
  BUSINESS_NAME STRING,
  CITY STRING,
  STATE STRING
);

INSERT OVERWRITE INTO DIM_BUSINESS (BUSINESS_ID, BUSINESS_NAME, CITY, STATE)
SELECT DISTINCT BUSINESS_ID, BUSINESS_NAME, CITY, STATE
FROM ODS.REVIEW_WITH_WEATHER;

-- Customer dimension
CREATE OR REPLACE TABLE DIM_CUSTOMER (
  CUSTOMER_KEY INT AUTOINCREMENT PRIMARY KEY,
  CUSTOMER_ID STRING UNIQUE
);

INSERT OVERWRITE INTO DIM_CUSTOMER (CUSTOMER_ID)
SELECT DISTINCT CUSTOMER_ID
FROM ODS.REVIEW_WITH_WEATHER;

-- Weather dimension (daily weather facts)
CREATE OR REPLACE TABLE DIM_WEATHER (
  WEATHER_KEY INT AUTOINCREMENT PRIMARY KEY,
  DATE_KEY INT,
  TMIN_F FLOAT,
  TMAX_F FLOAT,
  NORMAL_MIN_F FLOAT,
  NORMAL_MAX_F FLOAT,
  PRECIP_IN FLOAT,
  PRECIP_NORMAL_IN FLOAT
);

INSERT OVERWRITE INTO DIM_WEATHER (DATE_KEY, TMIN_F, TMAX_F, NORMAL_MIN_F, NORMAL_MAX_F, PRECIP_IN, PRECIP_NORMAL_IN)
SELECT DISTINCT
  TO_NUMBER(TO_CHAR(COALESCE(t.WX_DATE, p.WX_DATE), 'YYYYMMDD')) AS DATE_KEY,
  t.TMIN_F,
  t.TMAX_F,
  t.NORMAL_MIN_F,
  t.NORMAL_MAX_F,
  p.PRECIP_IN,
  p.PRECIP_NORMAL_IN
FROM ODS.TEMPERATURE t
FULL OUTER JOIN ODS.PRECIPITATION p
  ON p.WX_DATE = t.WX_DATE
WHERE COALESCE(t.WX_DATE, p.WX_DATE) IS NOT NULL;

-- Fact table keyed by dimensions
CREATE OR REPLACE TABLE FACT_REVIEW (
  FACT_ID INT AUTOINCREMENT PRIMARY KEY,
  DATE_KEY INT,
  BUSINESS_KEY INT,
  CUSTOMER_KEY INT,
  WEATHER_KEY INT,
  STARS NUMBER(2,1)
);

INSERT OVERWRITE INTO FACT_REVIEW (DATE_KEY, BUSINESS_KEY, CUSTOMER_KEY, WEATHER_KEY, STARS)
SELECT
  d.DATE_KEY,
  b.BUSINESS_KEY,
  c.CUSTOMER_KEY,
  w.WEATHER_KEY,
  r.STARS
FROM ODS.REVIEW_WITH_WEATHER r
JOIN DIM_DATE     d ON d.FULL_DATE   = r.REVIEW_DATE
JOIN DIM_BUSINESS b ON b.BUSINESS_ID = r.BUSINESS_ID
JOIN DIM_CUSTOMER c ON c.CUSTOMER_ID = r.CUSTOMER_ID
LEFT JOIN DIM_WEATHER w ON w.DATE_KEY = d.DATE_KEY;

-- Evidence for DWH load
SELECT
  (SELECT COUNT(*) FROM DIM_DATE)     AS DIM_DATE_ROWS,
  (SELECT COUNT(*) FROM DIM_BUSINESS) AS DIM_BUS_ROWS,
  (SELECT COUNT(*) FROM DIM_CUSTOMER) AS DIM_CUST_ROWS,
  (SELECT COUNT(*) FROM DIM_WEATHER)  AS DIM_WX_ROWS,
  (SELECT COUNT(*) FROM FACT_REVIEW)  AS FACT_REVIEW_ROWS;
