USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_YELP_XS;
USE DATABASE YELP_WEATHER;
USE SCHEMA DWH;

SELECT
  b.BUSINESS_NAME,
  d.FULL_DATE        AS REVIEW_DATE,
  COALESCE(w.TMIN_F, w.NORMAL_MIN_F)           AS TEMP_MIN_F,
  COALESCE(w.TMAX_F, w.NORMAL_MAX_F)           AS TEMP_MAX_F,
  w.NORMAL_MIN_F     AS NORMAL_MIN_F,
  w.NORMAL_MAX_F     AS NORMAL_MAX_F,
  COALESCE(w.PRECIP_IN, w.PRECIP_NORMAL_IN)    AS PRECIP_IN,
  w.PRECIP_NORMAL_IN AS PRECIP_NORMAL_IN,
  f.STARS            AS RATING
FROM FACT_REVIEW f
JOIN DIM_BUSINESS b ON f.BUSINESS_KEY = b.BUSINESS_KEY
JOIN DIM_DATE     d ON f.DATE_KEY     = d.DATE_KEY
LEFT JOIN DIM_WEATHER w ON f.WEATHER_KEY = w.WEATHER_KEY
ORDER BY REVIEW_DATE DESC, BUSINESS_NAME
LIMIT 50;
