USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_YELP_XS;
USE DATABASE YELP_WEATHER;

WITH storage AS (
  SELECT
    TABLE_SCHEMA,
    TABLE_NAME,
    MAX(COALESCE(ACTIVE_BYTES,0) + COALESCE(TIME_TRAVEL_BYTES,0) + COALESCE(FAILSAFE_BYTES,0)) AS BYTES
  FROM INFORMATION_SCHEMA.TABLE_STORAGE_METRICS
  WHERE TABLE_SCHEMA IN ('STG','ODS')
  GROUP BY TABLE_SCHEMA, TABLE_NAME
), counts AS (
  SELECT
    TABLE_SCHEMA,
    TABLE_NAME,
    ROW_COUNT
  FROM INFORMATION_SCHEMA.TABLES
  WHERE TABLE_SCHEMA IN ('STG','ODS')
    AND TABLE_TYPE = 'BASE TABLE'
)
SELECT
  c.TABLE_SCHEMA,
  c.TABLE_NAME,
  c.ROW_COUNT,
  COALESCE(s.BYTES, 0) AS BYTES
FROM counts c
LEFT JOIN storage s
  ON c.TABLE_SCHEMA = s.TABLE_SCHEMA
 AND c.TABLE_NAME = s.TABLE_NAME
ORDER BY c.TABLE_SCHEMA, c.TABLE_NAME;

LIST @STG.YELP_STAGE;
LIST @STG.CLIMATE_STAGE;
