USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_YELP_XS;
USE DATABASE YELP_WEATHER;

-- Remove legacy staging tables
DROP TABLE IF EXISTS STG.BUSINESS_JSON;
DROP TABLE IF EXISTS STG.REVIEW_JSON;

-- Drop obsolete ODS helper views/tables
DROP VIEW  IF EXISTS ODS.TEMPERATURE_CSV;
DROP VIEW  IF EXISTS ODS.TEMPERATURE_CSV_STD;
DROP VIEW  IF EXISTS ODS.PRECIPITATION_CSV;
DROP VIEW  IF EXISTS ODS.PRECIPITATION_CSV_STD;
DROP VIEW  IF EXISTS ODS.BUSINESS_NORM;
DROP VIEW  IF EXISTS ODS.REVIEW_NORM;
DROP VIEW  IF EXISTS ODS.REVIEW_WITH_WEATHER_DATE;
DROP VIEW  IF EXISTS ODS.REVIEW_WITH_WEATHER_DOY;

-- Drop superseded DWH artifacts
DROP VIEW  IF EXISTS DWH.WEATHER_CURATED;
