USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_YELP_XS;
USE DATABASE YELP_WEATHER;
USE SCHEMA DWH;

-- Empty fact first to avoid dependency issues
TRUNCATE TABLE IF EXISTS FACT_REVIEW;

-- Then reset dimensions
TRUNCATE TABLE IF EXISTS DIM_WEATHER;
TRUNCATE TABLE IF EXISTS DIM_CUSTOMER;
TRUNCATE TABLE IF EXISTS DIM_BUSINESS;
TRUNCATE TABLE IF EXISTS DIM_DATE;
